# CMake generated Testfile for 
# Source directory: /home/runner/work/isa-l/isa-l
# Build directory: /home/runner/work/isa-l/isa-l/_codeql_build_dir
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(gf_vect_mul_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/gf_vect_mul_test")
set_tests_properties(gf_vect_mul_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/erasure_code.cmake;227;add_test;/home/runner/work/isa-l/isa-l/cmake/erasure_code.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;122;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(erasure_code_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/erasure_code_test")
set_tests_properties(erasure_code_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/erasure_code.cmake;227;add_test;/home/runner/work/isa-l/isa-l/cmake/erasure_code.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;122;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(gf_inverse_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/gf_inverse_test")
set_tests_properties(gf_inverse_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/erasure_code.cmake;227;add_test;/home/runner/work/isa-l/isa-l/cmake/erasure_code.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;122;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(erasure_code_update_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/erasure_code_update_test")
set_tests_properties(erasure_code_update_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/erasure_code.cmake;227;add_test;/home/runner/work/isa-l/isa-l/cmake/erasure_code.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;122;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(xor_gen_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/xor_gen_test")
set_tests_properties(xor_gen_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/raid.cmake;108;add_test;/home/runner/work/isa-l/isa-l/cmake/raid.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;123;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(pq_gen_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/pq_gen_test")
set_tests_properties(pq_gen_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/raid.cmake;108;add_test;/home/runner/work/isa-l/isa-l/cmake/raid.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;123;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(xor_check_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/xor_check_test")
set_tests_properties(xor_check_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/raid.cmake;108;add_test;/home/runner/work/isa-l/isa-l/cmake/raid.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;123;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(pq_check_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/pq_check_test")
set_tests_properties(pq_check_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/raid.cmake;108;add_test;/home/runner/work/isa-l/isa-l/cmake/raid.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;123;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(crc16_t10dif_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/crc16_t10dif_test")
set_tests_properties(crc16_t10dif_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/crc.cmake;138;add_test;/home/runner/work/isa-l/isa-l/cmake/crc.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;124;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(crc16_t10dif_copy_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/crc16_t10dif_copy_test")
set_tests_properties(crc16_t10dif_copy_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/crc.cmake;138;add_test;/home/runner/work/isa-l/isa-l/cmake/crc.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;124;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(crc64_funcs_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/crc64_funcs_test")
set_tests_properties(crc64_funcs_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/crc.cmake;138;add_test;/home/runner/work/isa-l/isa-l/cmake/crc.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;124;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(crc32_funcs_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/crc32_funcs_test")
set_tests_properties(crc32_funcs_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/crc.cmake;138;add_test;/home/runner/work/isa-l/isa-l/cmake/crc.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;124;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(igzip_rand_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/igzip_rand_test")
set_tests_properties(igzip_rand_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/igzip.cmake;137;add_test;/home/runner/work/isa-l/isa-l/cmake/igzip.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;125;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(igzip_wrapper_hdr_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/igzip_wrapper_hdr_test")
set_tests_properties(igzip_wrapper_hdr_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/igzip.cmake;137;add_test;/home/runner/work/isa-l/isa-l/cmake/igzip.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;125;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(checksum32_funcs_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/checksum32_funcs_test")
set_tests_properties(checksum32_funcs_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/igzip.cmake;137;add_test;/home/runner/work/isa-l/isa-l/cmake/igzip.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;125;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(mem_zero_detect_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/mem_zero_detect_test")
set_tests_properties(mem_zero_detect_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/mem.cmake;92;add_test;/home/runner/work/isa-l/isa-l/cmake/mem.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;126;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
add_test(version_test "/home/runner/work/isa-l/isa-l/_codeql_build_dir/version_test")
set_tests_properties(version_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/isa-l/isa-l/cmake/misc.cmake;48;add_test;/home/runner/work/isa-l/isa-l/cmake/misc.cmake;0;;/home/runner/work/isa-l/isa-l/CMakeLists.txt;127;include;/home/runner/work/isa-l/isa-l/CMakeLists.txt;0;")
